cohort: "BLCA"
cohort_csv: "/mnt/Xsky/zqb/TDAE/data/csvs/TCGA_BLCA_survival_dx.csv"
tasks:
  classification:
    enabled: false
  survival:
    enabled: true
    task: "survival"
    label_column: "cancer_code"
