cohort: "UCEC"
cohort_csv: "/mnt/Xsky/zqb/TDAE/data/csvs/TCGA_UCEC_survival_dx.csv"
tasks:
  classification:
    enabled: false
    task: "classification"
    label_column: "primary_diagnosis"
    include_labels:
      - "Endometrioid adenocarcinoma, NOS"
      - "Serous cystadenocarcinoma, NOS"
    label_aliases:
      "Endometrioid adenocarcinoma, NOS": "Endometrioid"
      "Serous cystadenocarcinoma, NOS": "Serous"
  survival:
    enabled: true
    task: "survival"
    label_column: "primary_diagnosis"
