encoder_name: "ctranspath"
model_path: "/mnt/Xsky/public_model_zoo/CHIEF/model_weight/CHIEF_CTransPath.pth"
d_full: 768
d_light: 96
d_medium: 192
truncate_layer: 1
medium_layer: 2
full_batch_size: 256
light_batch_size: 512
flops_cost: [0.08, 0.08, 0.20, 1.0]
