encoder_name: "uni2"
model_path: "/mnt/Xsky/models/PFM/UNI2-h"
d_full: 1536
d_light: 1536
d_medium: 1536
truncate_layer: 3
medium_layer: 12
full_batch_size: 64
light_batch_size: 256
flops_cost: [0.125, 0.125, 0.5, 1.0]
